# Generated by Django 4.0.3 on 2023-02-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('event_id', models.IntegerField()),
                ('event_description', models.CharField(max_length=200)),
                ('event_duration', models.CharField(max_length=50)),
                ('reviews', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback_id', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('hotel_id', models.IntegerField()),
                ('hotel_contact', models.CharField(max_length=25)),
                ('hotel_reviews', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='TouristSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('spot_id', models.IntegerField()),
                ('location', models.CharField(max_length=25)),
                ('current_weather', models.CharField(max_length=122)),
                ('current_road_conditions', models.CharField(max_length=122)),
                ('reviews', models.CharField(max_length=250)),
                ('hotel_services', models.CharField(max_length=250)),
                ('car_rentals', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportation_id', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('name', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TravelAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('user_id', models.IntegerField()),
                ('mobile', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=122)),
                ('travel_history', models.CharField(max_length=122)),
                ('reviews', models.CharField(max_length=250)),
            ],
        ),
    ]
